# Generated by Django 5.2.4 on 2025-07-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_product_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(default="", max_length=128),
            preserve_default=False,
        ),
    ]
