# Generated by Django 5.2.4 on 2025-07-14 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_cart"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="products",
            new_name="Orders",
        ),
    ]
