# Generated by Django 5.2.4 on 2025-07-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_rename_products_cart_orders"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="date_ordered",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
