# Generated by Django 5.2.4 on 2025-07-14 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_alter_cart_date_ordered"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="Orders",
            new_name="orders",
        ),
    ]
