# Generated by Django 5.2.4 on 2025-07-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_rename_orders_cart_orders"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date_ordered",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
