# Generated by Django 5.2.4 on 2025-07-14 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_alter_order_date_ordered"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="date_ordered",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="ordered",
        ),
    ]
