# Generated by Django 5.2.4 on 2025-07-15 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_category_product_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={},
        ),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
    ]
