# Generated by Django 5.2.4 on 2025-07-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0015_product_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["display_order", "name"],
                "verbose_name": "Catégorie",
                "verbose_name_plural": "Catégories",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="color_theme",
            field=models.CharField(
                default="#6c757d",
                help_text="Couleur thème en hexa (#ffffff)",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="display_order",
            field=models.PositiveIntegerField(
                default=0, help_text="Ordre d'affichage (0 = premier)"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="icon_class",
            field=models.CharField(
                blank=True,
                help_text="Classe CSS de l'icône (ex: fas fa-tshirt)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Catégorie active et visible"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="is_featured",
            field=models.BooleanField(
                default=False, help_text="Afficher sur la page d'accueil"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="meta_description",
            field=models.CharField(
                blank=True, help_text="Description pour SEO", max_length=160
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="meta_keywords",
            field=models.CharField(
                blank=True,
                help_text="Mots-clés SEO séparés par des virgules",
                max_length=255,
            ),
        ),
    ]
