# Generated by Django 5.2.4 on 2025-07-16 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0016_alter_category_options_category_color_theme_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-created_at"]},
        ),
    ]
