# Generated by Django 5.2.4 on 2025-07-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0017_alter_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="shoe_size",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Pointure de chaussure (ex: 38.5)",
                max_digits=4,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("XS", "XS"),
                    ("S", "S"),
                    ("M", "M"),
                    ("L", "L"),
                    ("XL", "XL"),
                    ("XXL", "XXL"),
                ],
                help_text="Taille du vêtement",
                max_length=8,
                null=True,
            ),
        ),
    ]
