# Generated by Django 5.2.4 on 2025-07-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0019_remove_product_size_remove_product_stock_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="size",
            field=models.CharField(
                blank=True,
                help_text="Taille sélectionnée (ex: M, 42, Unique)",
                max_length=10,
                null=True,
            ),
        ),
    ]
