name: yee-ecommerce
services:
- name: web
  source_dir: /
  github:
    repo: Flamingo12345678/E-Commerce
    branch: main
    deploy_on_push: true

  run_command: gunicorn --worker-tmp-dir /dev/shm shop.wsgi:application

  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs

  http_port: 8080

  health_check:
    http_path: /
    initial_delay_seconds: 20
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3

  envs:
  - key: DEBUG
    value: "False"
  - key: DJANGO_SETTINGS_MODULE
    value: "shop.settings"
  - key: ALLOWED_HOSTS
    value: "y-e-e.codes,www.y-e-e.codes,*.ondigitalocean.app"
  - key: STATIC_ROOT
    value: "/app/staticfiles"
  - key: MEDIA_ROOT
    value: "/app/media"
  - key: SECURE_SSL_REDIRECT
    value: "True"
  - key: SECURE_PROXY_SSL_HEADER
    value: "HTTP_X_FORWARDED_PROTO,https"
  - key: SECRET_KEY
    scope: RUN_TIME
    type: SECRET
  - key: STRIPE_PUBLISHABLE_KEY
    scope: RUN_TIME
    type: SECRET
  - key: STRIPE_SECRET_KEY
    scope: RUN_TIME
    type: SECRET
  - key: STRIPE_WEBHOOK_SECRET
    scope: RUN_TIME
    type: SECRET
  - key: PAYPAL_CLIENT_ID
    scope: RUN_TIME
    type: SECRET
  - key: PAYPAL_CLIENT_SECRET
    scope: RUN_TIME
    type: SECRET
  - key: EMAIL_HOST_USER
    scope: RUN_TIME
    type: SECRET
  - key: EMAIL_HOST_PASSWORD
    scope: RUN_TIME
    type: SECRET
  - key: FIREBASE_CREDENTIALS
    scope: RUN_TIME
    type: SECRET

databases:
- name: yee
  engine: PG
  version: "14"
  size: basic
  num_nodes: 1
