# Generated by Django 5.2.4 on 2025-07-31 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="store.product",
                verbose_name="Produit",
            ),
        ),
        migrations.AddField(
            model_name="invoicepayment",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="accounts.invoice",
                verbose_name="Facture",
            ),
        ),
        migrations.AddField(
            model_name="invoicereminder",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reminders",
                to="accounts.invoice",
                verbose_name="Facture",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.invoicetemplate",
                verbose_name="Template",
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_methods",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AddField(
            model_name="recurringinvoicetemplate",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recurring_invoices",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Client",
            ),
        ),
        migrations.AddField(
            model_name="recurringinvoicetemplate",
            name="template",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.invoicetemplate",
                verbose_name="Template de facture",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="payment_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.paymentmethod",
                verbose_name="Méthode de paiement",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AddIndex(
            model_name="webhooklog",
            index=models.Index(
                fields=["provider", "event_type"], name="accounts_we_provide_b3f22f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webhooklog",
            index=models.Index(
                fields=["received_at"], name="accounts_we_receive_e8f07e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webhooklog",
            index=models.Index(
                fields=["processed_successfully"], name="accounts_we_process_fe1b5a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="invoicereminder",
            unique_together={("invoice", "reminder_type", "days_offset")},
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["invoice_number"], name="accounts_in_invoice_72c085_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["status"], name="accounts_in_status_08f461_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["due_date"], name="accounts_in_due_dat_309676_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["customer"], name="accounts_in_custome_333ca6_idx"
            ),
        ),
    ]
