# Generated by Django 5.2.4 on 2025-07-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_shopper_options_shopper_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopper",
            name="email_notifications",
            field=models.BooleanField(
                default=True, verbose_name="Notifications par email"
            ),
        ),
        migrations.AddField(
            model_name="shopper",
            name="push_notifications",
            field=models.BooleanField(default=True, verbose_name="Notifications push"),
        ),
        migrations.AddField(
            model_name="shopper",
            name="sms_notifications",
            field=models.BooleanField(
                default=False, verbose_name="Notifications par SMS"
            ),
        ),
    ]
