# Generated by Django 5.2.4 on 2025-07-15 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_shopper_email_notifications_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address_type",
                    models.CharField(
                        choices=[
                            ("home", "Domicile"),
                            ("work", "Travail"),
                            ("other", "Autre"),
                        ],
                        default="home",
                        max_length=10,
                    ),
                ),
                ("street", models.CharField(max_length=255, verbose_name="Rue")),
                ("city", models.CharField(max_length=100, verbose_name="Ville")),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="État/Province"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(max_length=20, verbose_name="Code postal"),
                ),
                (
                    "country",
                    models.CharField(
                        default="France", max_length=100, verbose_name="Pays"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, verbose_name="Adresse par défaut"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Adresse",
                "verbose_name_plural": "Adresses",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
    ]
