# Generated by Django 5.2.4 on 2025-08-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_emailtemplate_emailtestsend"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtestsend",
            name="test_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Variables JSON pour tester le template",
                verbose_name="Données de test",
            ),
        ),
    ]
