# Generated by Django 5.2.4 on 2025-08-25 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_email_templates"),
        ("accounts", "0004_alter_emailtestsend_test_data"),
    ]

    operations = []
