# Generated by Django 5.2.4 on 2025-07-16 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_shopper_two_factor_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card_type",
                    models.CharField(
                        choices=[
                            ("visa", "Visa"),
                            ("mastercard", "Mastercard"),
                            ("amex", "American Express"),
                            ("discover", "Discover"),
                            ("other", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Type de carte",
                    ),
                ),
                (
                    "card_number_hash",
                    models.CharField(
                        max_length=64, verbose_name="Hash du numéro de carte"
                    ),
                ),
                (
                    "last4",
                    models.CharField(max_length=4, verbose_name="4 derniers chiffres"),
                ),
                (
                    "cardholder_name",
                    models.CharField(max_length=100, verbose_name="Nom du porteur"),
                ),
                ("expiry_month", models.IntegerField(verbose_name="Mois d'expiration")),
                ("expiry_year", models.IntegerField(verbose_name="Année d'expiration")),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, verbose_name="Méthode par défaut"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Méthode de paiement",
                "verbose_name_plural": "Méthodes de paiement",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
    ]
