# Generated by Django 5.2.4 on 2025-07-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="error_message",
            field=models.TextField(blank=True, verbose_name="Message d'erreur"),
        ),
    ]
