# Generated by Django 5.2.4 on 2025-07-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_paymentmethod_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrphanTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        max_length=20, verbose_name="Fournisseur de paiement"
                    ),
                ),
                (
                    "provider_transaction_id",
                    models.CharField(
                        max_length=255, verbose_name="ID transaction fournisseur"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Montant"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="EUR", max_length=3, verbose_name="Devise"
                    ),
                ),
                ("status", models.CharField(max_length=50, verbose_name="Statut")),
                (
                    "provider_data",
                    models.JSONField(verbose_name="Données complètes du fournisseur"),
                ),
                (
                    "webhook_received_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Reçu le"),
                ),
                (
                    "investigated",
                    models.BooleanField(
                        default=False, verbose_name="Enquête effectuée"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Notes d'investigation"),
                ),
            ],
            options={
                "verbose_name": "Transaction orpheline",
                "verbose_name_plural": "Transactions orphelines",
                "ordering": ["-webhook_received_at"],
            },
        ),
        migrations.CreateModel(
            name="WebhookLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("stripe", "Stripe"), ("paypal", "PayPal")],
                        max_length=20,
                        verbose_name="Fournisseur",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(max_length=100, verbose_name="Type d'événement"),
                ),
                (
                    "event_id",
                    models.CharField(max_length=255, verbose_name="ID d'événement"),
                ),
                ("payload", models.JSONField(verbose_name="Payload complet")),
                (
                    "signature_valid",
                    models.BooleanField(default=False, verbose_name="Signature valide"),
                ),
                (
                    "processed_successfully",
                    models.BooleanField(
                        default=False, verbose_name="Traité avec succès"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Message d'erreur"),
                ),
                (
                    "processing_time_ms",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Temps de traitement (ms)"
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Reçu le"),
                ),
            ],
            options={
                "verbose_name": "Log de webhook",
                "verbose_name_plural": "Logs de webhooks",
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(
                        fields=["provider", "event_type"],
                        name="accounts_we_provide_b3f22f_idx",
                    ),
                    models.Index(
                        fields=["received_at"], name="accounts_we_receive_e8f07e_idx"
                    ),
                    models.Index(
                        fields=["processed_successfully"],
                        name="accounts_we_process_fe1b5a_idx",
                    ),
                ],
            },
        ),
    ]
