# Generated by Django 5.2.4 on 2025-07-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_orphantransaction_webhooklog"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopper",
            name="paypal_customer_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID Client PayPal"
            ),
        ),
        migrations.AddField(
            model_name="shopper",
            name="stripe_customer_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID Client Stripe"
            ),
        ),
    ]
