# Generated by Django 5.2.4 on 2025-07-16 21:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_shopper_paypal_customer_id_and_more"),
        ("store", "0017_alter_product_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nom du template"),
                ),
                (
                    "company_name",
                    models.CharField(
                        max_length=200, verbose_name="Nom de l'entreprise"
                    ),
                ),
                (
                    "company_address",
                    models.TextField(verbose_name="Adresse de l'entreprise"),
                ),
                (
                    "company_logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="invoice_templates/",
                        verbose_name="Logo de l'entreprise",
                    ),
                ),
                (
                    "footer_text",
                    models.TextField(blank=True, verbose_name="Texte de pied de page"),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=20.0,
                        max_digits=5,
                        verbose_name="Taux de TVA (%)",
                    ),
                ),
                (
                    "payment_terms",
                    models.TextField(
                        default="Paiement à réception de facture",
                        verbose_name="Conditions de paiement",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, verbose_name="Template par défaut"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Template de facture",
                "verbose_name_plural": "Templates de factures",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Numéro de facture"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("sent", "Envoyée"),
                            ("paid", "Payée"),
                            ("overdue", "En retard"),
                            ("cancelled", "Annulée"),
                            ("refunded", "Remboursée"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Date d'émission",
                    ),
                ),
                ("due_date", models.DateField(verbose_name="Date d'échéance")),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Sous-total HT",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Montant TVA",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Remise",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Total TTC",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("stripe", "Stripe"),
                            ("paypal", "PayPal"),
                            ("bank_transfer", "Virement bancaire"),
                            ("cash", "Espèces"),
                            ("check", "Chèque"),
                            ("other", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Méthode de paiement",
                    ),
                ),
                (
                    "paid_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de paiement"
                    ),
                ),
                (
                    "stripe_invoice_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="ID facture Stripe",
                    ),
                ),
                (
                    "paypal_invoice_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="ID facture PayPal",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "terms_and_conditions",
                    models.TextField(blank=True, verbose_name="CGV"),
                ),
                (
                    "currency",
                    models.CharField(
                        default="EUR", max_length=3, verbose_name="Devise"
                    ),
                ),
                (
                    "sent_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'envoi"
                    ),
                ),
                (
                    "viewed_date",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Date de première consultation",
                    ),
                ),
                (
                    "reminder_sent_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de rappels envoyés"
                    ),
                ),
                (
                    "last_reminder_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date du dernier rappel"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Client",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.invoicetemplate",
                        verbose_name="Template",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facture",
                "verbose_name_plural": "Factures",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Description"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        max_digits=10,
                        verbose_name="Quantité",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix unitaire"
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Total ligne",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="accounts.invoice",
                        verbose_name="Facture",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="store.product",
                        verbose_name="Produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de facture",
                "verbose_name_plural": "Lignes de facture",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="InvoicePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Montant"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("paypal", "PayPal"),
                            ("bank_transfer", "Virement bancaire"),
                            ("cash", "Espèces"),
                            ("check", "Chèque"),
                            ("other", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Méthode de paiement",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("processing", "En cours"),
                            ("completed", "Terminé"),
                            ("failed", "Échoué"),
                            ("cancelled", "Annulé"),
                            ("refunded", "Remboursé"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="PaymentIntent Stripe",
                    ),
                ),
                (
                    "paypal_payment_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Payment ID PayPal",
                    ),
                ),
                (
                    "transaction_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Frais de transaction",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de completion"
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="accounts.invoice",
                        verbose_name="Facture",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement de facture",
                "verbose_name_plural": "Paiements de factures",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecurringInvoiceTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nom du modèle"),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("weekly", "Hebdomadaire"),
                            ("monthly", "Mensuelle"),
                            ("quarterly", "Trimestrielle"),
                            ("yearly", "Annuelle"),
                        ],
                        max_length=20,
                        verbose_name="Fréquence",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Date de début")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="Date de fin"),
                ),
                (
                    "next_invoice_date",
                    models.DateField(verbose_name="Prochaine facture"),
                ),
                (
                    "description_template",
                    models.TextField(verbose_name="Template de description"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Montant"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "auto_send",
                    models.BooleanField(
                        default=False, verbose_name="Envoi automatique"
                    ),
                ),
                (
                    "invoices_generated",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Factures générées"
                    ),
                ),
                (
                    "last_generated",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernière génération"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_invoices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Client",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.invoicetemplate",
                        verbose_name="Template de facture",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facture récurrente",
                "verbose_name_plural": "Factures récurrentes",
                "ordering": ["next_invoice_date"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("before_due", "Avant échéance"),
                            ("on_due_date", "Le jour de l'échéance"),
                            ("after_due", "Après échéance"),
                        ],
                        max_length=20,
                        verbose_name="Type de rappel",
                    ),
                ),
                ("days_offset", models.IntegerField(verbose_name="Décalage en jours")),
                (
                    "sent_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'envoi"
                    ),
                ),
                (
                    "email_sent",
                    models.BooleanField(default=False, verbose_name="Email envoyé"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="accounts.invoice",
                        verbose_name="Facture",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rappel de facture",
                "verbose_name_plural": "Rappels de factures",
                "ordering": ["days_offset"],
                "unique_together": {("invoice", "reminder_type", "days_offset")},
            },
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["invoice_number"], name="accounts_in_invoice_72c085_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["status"], name="accounts_in_status_08f461_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["due_date"], name="accounts_in_due_dat_309676_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["customer"], name="accounts_in_custome_333ca6_idx"
            ),
        ),
    ]
