# Generated by Django 5.2.4 on 2025-07-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0012_invoicetemplate_invoice_invoiceitem_invoicepayment_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="shopper",
            name="firebase_uid",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                unique=True,
                verbose_name="Firebase UID",
            ),
        ),
    ]
