# GitHub Actions workflow pour déploiement continu Django E-Commerce sur Azure
name: Deploy Django E-Commerce to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: flam-ecommerce-1754047481
  PYTHON_VERSION: '3.11'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: 'Create and activate virtual environment'
      run: |
        python -m venv venv
        source venv/bin/activate
        echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH
        echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV

    - name: 'Install dependencies'
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: 'Run Django tests'
      run: |
        python manage.py test --verbosity=2
      env:
        SECRET_KEY: 'test-secret-key-for-ci-django-ecommerce-2025'
        DEBUG: 'True'
        ALLOWED_HOSTS: 'localhost,127.0.0.1'
        DB_NAME: 'test_db'
        DB_USER: 'test_user'
        DB_PASSWORD: 'test_password'
        DB_HOST: 'localhost'
        DB_PORT: '3306'
        STRIPE_PUBLISHABLE_KEY: 'fake_pk_test_key'
        STRIPE_SECRET_KEY: 'fake_sk_test_key'
        STRIPE_WEBHOOK_SECRET: 'fake_webhook_secret'
        PAYPAL_CLIENT_ID: 'fake_paypal_client'
        PAYPAL_CLIENT_SECRET: 'fake_paypal_secret'
        PAYPAL_MODE: 'sandbox'

    - name: 'Collect static files'
      run: |
        python manage.py collectstatic --noinput
      env:
        SECRET_KEY: 'test-secret-key-for-ci-django-ecommerce-2025'
        DEBUG: 'False'
        ALLOWED_HOSTS: 'localhost,127.0.0.1'
        DB_NAME: 'test_db'
        DB_USER: 'test_user'
        DB_PASSWORD: 'test_password'
        DB_HOST: 'localhost'
        DB_PORT: '3306'

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: '.'
        startup-file: 'startup.sh'
