name: Deploy to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout code'
      uses: actions/checkout@v4

    - name: 'Set up Python'
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: 'Install dependencies'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 'Run tests'
      env:
        DATABASE_URL: 'sqlite:///:memory:'
        DEBUG: 'True'
        SECRET_KEY: 'test-secret-key-for-ci'
        ALLOWED_HOSTS: 'localhost,127.0.0.1'
      run: |
        python manage.py test

    # Azure Login avec les bonnes variables d'environnement
    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Alternative : Login avec des secrets individuels
    - name: 'Login to Azure (Alternative)'
      if: failure()
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'flam-ecommerce-1754047481'
        slot-name: 'production'
        package: '.'

    - name: 'Run Database Migrations on Azure'
      env:
        SCM_DO_BUILD_DURING_DEPLOYMENT: 'true'
      run: |
        # Attendre que l'app soit disponible
        sleep 30
        
        # Exécuter les migrations via Kudu API (optionnel)
        echo "Déploiement terminé. Vérifiez les migrations dans le portail Azure."
